apiVersion: v1
kind: Service
metadata:
  name: connect
  namespace: kafka
spec:
  ports:
  - name: "8083"
    port: 8083
    targetPort: 8083
  - name: "5005"
    port: 5005
    targetPort: 5005
  selector:
    io.kompose.service: connect
status:
  loadBalancer: {}
