apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: postgres
  namespace: kafka
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: postgres
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: inventory
        - name: POSTGRES_PASSWORD
          value: postgrespw
        - name: POSTGRES_USER
          value: postgresuser
        image: debezium/postgres:9.6
        name: postgres
        ports:
        - containerPort: 5432
        resources: {}
      restartPolicy: Always
status: {}
